#!name=Bing积分
#!desc=2023.8.19 记得到boxjs里面设置每日任务重置时间，不设置默认每天早上8点
# 作者 lowking


[MITM]
hostname = %APPEND% rewards.bing.com

[Script]
# > Bing积分
Bing积分cookie = requires-body=0,type=http-request,pattern=https:\/\/rewards\.bing\.com,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/bing/bingPoint.js
Bing积分 = type=cron,cronexp="0 10 0 * * ?",wake-system=1,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/bing/bingPoint.js
