#!name=朴朴签到-lowking-v2.0.6
#!desc=2023.8.19 手机朴朴短信登录获取token


[MITM]
hostname = %APPEND% cauth.pupuapi.com


[Script]
# > 朴朴签到
朴朴签到cookie = requires-body=1,type=http-response,pattern=https:\/\/cauth.pupuapi.com\/clientauth\/user\/verify_login,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/pupu/pupuCheckIn.js
朴朴签到 = type=cron,cronexp="0 10 0 * * ?",wake-system=1,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/pupu/pupuCheckIn.js

