#朴朴签到-lowking-v2.0.6
#按下面配置完之后，手机朴朴短信登录获取token，下面配置只验证过surge的，其他的自行测试



[Script]
# > 朴朴签到
朴朴签到cookie = requires-body=1,type=http-response,pattern=https:\/\/cauth.pupuapi.com\/clientauth\/user\/verify_login,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/pupu/pupuCheckIn.js
朴朴签到 = type=cron,cronexp="0 10 0 * * ?",wake-system=1,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/pupu/pupuCheckIn.js

[MITM]
hostname = %APPEND% cauth.pupuapi.com
